# Generated by Django 4.2.2 on 2023-12-17 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='mname',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
