# Generated by Django 4.2.2 on 2023-12-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0002_remove_accounts_mname_accounts_email_accounts_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
