# Generated by Django 4.2.2 on 2023-12-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
