# Generated by Django 4.2.2 on 2023-12-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='gender',
        ),
    ]
