# Generated by Django 4.2.2 on 2023-12-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0009_remove_accounts_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('increase_price', models.CharField(max_length=10)),
                ('min_deposit', models.CharField(max_length=10)),
                ('max_deposit', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=40)),
            ],
        ),
    ]
