# Generated by Django 4.2.2 on 2023-12-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0010_investment_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
