# Generated by Django 4.2.2 on 2023-12-19 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0012_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activated_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('depositedAmount', models.CharField(max_length=50)),
                ('adate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
