# Generated by Django 4.2.2 on 2023-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0013_activated_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(default='Request Accepted: Processing', max_length=20)),
                ('accountnumber', models.CharField(max_length=200)),
            ],
        ),
    ]
