# Generated by Django 4.2.2 on 2023-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0014_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='user_requested',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
