# Generated by Django 4.2.2 on 2023-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0015_withdrawals_user_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='activated_plans',
            name='usern',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
