# Generated by Django 4.2.2 on 2023-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0018_admin_account_no_coin_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_request',
            name='id',
        ),
        migrations.AddField(
            model_name='deposit_request',
            name='no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
