# Generated by Django 4.2.2 on 2023-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0019_remove_deposit_request_id_deposit_request_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_request',
            name='no',
        ),
        migrations.AddField(
            model_name='deposit_request',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
