# Generated by Django 4.2.2 on 2023-12-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0022_alter_deposit_request_bitcoin_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acctb',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
