# Generated by Django 4.2.2 on 2023-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent', '0024_remove_investment_plans_min_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acctb',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='investment_plans',
            name='max_deposit',
            field=models.CharField(max_length=1000),
        ),
    ]
